[openai]
api_key = "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"

[outlook]
client_id = "your-outlook-client-id"
client_secret = "your-outlook-client-secret"
tenant_id = "your-tenant-id"
redirect_uri = "http://localhost"
sender_email = "you@yourdomain.com"
